name: myclone
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - absl-py=1.0.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py39h7f8727e_2
  - async-timeout=3.0.1=py_1000
  - attrs=21.4.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blinker=1.4=py_1
  - bottleneck=1.3.2=py39hdd57654_1
  - brotli=1.0.9=h7f98852_5
  - brotli-bin=1.0.9=h7f98852_5
  - brotlipy=0.7.0=py39h3811e60_1001
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2021.10.8=ha878542_0
  - cachetools=4.2.4=pyhd8ed1ab_0
  - certifi=2021.10.8=py39hf3d152e_1
  - cffi=1.14.6=py39h400218f_0
  - chardet=4.0.0=py39hf3d152e_2
  - charset-normalizer=2.0.10=pyhd8ed1ab_0
  - click=8.0.3=py39hf3d152e_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=35.0.0=py39hbca0aa6_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cvxpy=1.1.18=py39hf3d152e_0
  - cvxpy-base=1.1.18=py39hde0f152_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=he372182_0
  - ecos=2.0.10=py39hce5d2b2_0
  - expat=2.2.10=h9c3ff4c_0
  - fontconfig=2.13.1=hba837de_1005
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h0708190_1
  - fsspec=2022.1.0=pyhd8ed1ab_0
  - future=0.18.2=py39hf3d152e_4
  - glib=2.69.1=h5202010_0
  - google-auth=2.3.3=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - grpcio=1.42.0=py39hce63b2e_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=hf484d3e_1000
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.10.0=py39hf3d152e_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py39h2531618_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h7f98852_5
  - libbrotlidec=1.0.9=h7f98852_5
  - libbrotlienc=1.0.9=h7f98852_5
  - libcblas=3.9.0=12_linux64_mkl
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - liblapack=3.9.0=12_linux64_mkl
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.15.8=h780b84a_0
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.2.0=h85742a9_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.12=h03d6c58_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.3.6=pyhd8ed1ab_0
  - matplotlib=3.4.3=py39hf3d152e_2
  - matplotlib-base=3.4.3=py39hbbc1b5f_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h3811e60_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39hde0f152_0
  - multidict=5.2.0=py39h7f8727e_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.3=h7f8727e_2
  - numexpr=2.8.1=py39h6abb31d_0
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1l=h7f98852_0
  - osqp=0.6.2.post0=py39hde0f152_3
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.5=py39h8c16a72_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=7.2.0=py39h6f3857e_2
  - pip=21.2.4=py39h06a4308_0
  - protobuf=3.15.8=py39he80948d_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydeprecate=0.3.1=pyhd8ed1ab_0
  - pyjwt=2.3.0=pyhd8ed1ab_1
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39hf3d152e_4
  - python=3.9.7=h12debd9_1
  - python_abi=3.9=2_cp39
  - pytorch=1.10.1=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-lightning=1.5.8=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2020.1=py_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=5.4.1=py39h3811e60_0
  - qdldl-python=0.1.5=py39hde0f152_2
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd8ed1ab_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.8=pyhd8ed1ab_0
  - scipy=1.7.3=py39hee8e79c_0
  - scs=3.1.0=py39h3c5bb4f_0
  - setuptools=58.0.4=py39h06a4308_0
  - sip=4.19.13=py39h2531618_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=hc218d9a_0
  - tensorboard=2.7.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py39h3da14fd_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tk=8.6.11=h1ccaba5_0
  - torchmetrics=0.6.2=pyhd8ed1ab_0
  - tornado=6.1=py39h3811e60_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021e=hda174b7_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - werkzeug=2.0.1=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py39h3811e60_2
  - zipp=3.7.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=ha95c52a_0
  - pip:
    - anyio==3.5.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - babel==2.9.1
    - backcall==0.2.0
    - black==21.12b0
    - bleach==4.1.0
    - configparser==5.2.0
    - debugpy==1.5.1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - entrypoints==0.3
    - executing==0.8.2
    - gitdb==4.0.9
    - gitpython==3.1.26
    - ipykernel==6.7.0
    - ipython==8.0.1
    - ipython-genutils==0.2.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==4.4.0
    - jupyter-client==7.1.2
    - jupyter-core==4.9.1
    - jupyter-server==1.13.4
    - jupyterlab==3.2.8
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.10.3
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mypy-extensions==0.4.3
    - nbclassic==0.3.5
    - nbclient==0.5.10
    - nbconvert==6.4.1
    - nbformat==5.1.3
    - nest-asyncio==1.5.4
    - notebook==6.4.8
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==2.4.1
    - prometheus-client==0.13.1
    - promise==2.3
    - prompt-toolkit==3.0.26
    - psutil==5.9.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.11.2
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pyzmq==22.3.0
    - scikit-learn==1.0.2
    - send2trash==1.8.0
    - sentry-sdk==1.5.2
    - shortuuid==1.0.8
    - smmap==5.0.0
    - sniffio==1.2.0
    - stack-data==0.1.4
    - subprocess32==3.5.4
    - termcolor==1.1.0
    - terminado==0.13.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - tomli==1.2.3
    - traitlets==5.1.1
    - wandb==0.12.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.3
    - yaspin==2.1.0
prefix: /home/angelos/anaconda3/envs/myclone
